<?php
/* --
BEGINNER DEV NOTES: footer.php is used to generate the footer of each page of the WP site.
-- */
?>

<footer class="primary-color">
	<div class="footer-wrapper">
		<!-- add some PHP to only render this when set -->
		<?php
		if (has_nav_menu('footer_menu')):
			wp_nav_menu(array('container' => 'nav', 'menu_class' => 'origin-nav footer-nav', 'theme_location' => 'footer-menu'));
		endif;
		?>

	</div>
	<div class="footer-wrapper">
		<p class="footer-text">Blah blah blah! This is a footer!</p>
	</div>
	<div class="footer-wrapper">
		<p class="footer-text">Blah blah blah! This is a footer!</p>
	</div>
	<?php wp_footer(); ?> <!-- get the footer generated by functions.php -->
</footer>

</body>
</html>
