	<footer class="footer">
		<div class="footer__widgets">
			<?php
			if(is_active_sidebar('footer_widgets')) :
					dynamic_sidebar('footer_widgets');
				endif;
			?>
		</div>
		<?php wp_footer(); ?> <!-- get the footer generated by functions.php -->
	</footer>
</body>
</html>
