<footer class="primary-color">
	<?php
	if (has_nav_menu('footer_menu')):
		echo '<div class="footer-wrapper">';
			wp_nav_menu(array('container' => 'nav', 'menu_class' => 'origin-nav footer-nav', 'theme_location' => 'footer-menu'));
		echo '</div>';
	endif;

	// BUG: As soon as code hits the first empty text box the loop will stop
	for ($i = 1; get_theme_mod('footer_box_' . $i) != null; $i++) {
		echo '<div class="footer-wrapper">';
		echo '<p class="footer-text">' . get_theme_mod('footer_box_' . $i) . '</p>';
		echo '</div>';
	}
	?>
	<?php wp_footer(); ?> <!-- get the footer generated by functions.php -->
</footer>

</body>
</html>
